apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "user-mgmt-service.labels" . | nindent 4 }}
data:
  DATABASE_NAME: {{ .Values.config.databaseName | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.config.springDatasourceUrl | quote }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.config.springJpaHibernateDdlAuto | quote }}
  JWT_ISSUER: {{ .Values.config.jwtIssuer | quote }}
  JWT_EXPIRATION_MILLIS: {{ .Values.config.jwtExpirationMillis | quote }}
  INTERNAL_API_URL: {{ .Values.frontend.env.internalApiUrl | quote }}
