apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "user-mgmt-service.componentLabels" (dict "component" "frontend" "context" $) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "user-mgmt-service.componentSelectorLabels" (dict "component" "frontend" "context" $) | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
