apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "user-mgmt-service.componentLabels" (dict "component" "postgres" "context" $) | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}
  {{- if .Values.postgres.persistence.storageClassName }}
  storageClassName: {{ .Values.postgres.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
